services:
  server:
    build: 
      context: "."
      dockerfile: "./docker/server/Dockerfile"
      args:
        DEVELOPMENT: ${DEVELOPMENT}
    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app/server
      - type: bind
        source: ./client
        target: /usr/src/app/client
    ports:
      - "3000:3000"
      - "5173:5173"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://postgres:password@database/cryptochest
    env_file:
      - .env
  database:
    build: 
      context: "."
      dockerfile: "./docker/database/Dockerfile"
    restart: always
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080